# Generated by Django 5.0.3 on 2024-03-27 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('priority', models.IntegerField()),
                ('start_date', models.DateField()),
                ('dead_line', models.DateField()),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('staus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasktrack.status')),
            ],
        ),
    ]
