# Generated by Django 5.0.3 on 2024-04-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='staus',
            field=models.CharField(choices=[('notdone', 'Not Done'), ('in_progress', 'In Progress'), ('done', 'Done')], default='notdone', max_length=50),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
