# Generated by Django 5.0.3 on 2024-04-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrack', '0002_alter_task_staus_delete_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='staus',
            new_name='status',
        ),
    ]
